### ISSUE TITLE
start erro

### ISSUE THREAD

**Issue by MCDevel** [tobykurien/rpi_lcars#40] opened 2021-08-08 20:19 UTC
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "lcars.py", line 2, in <module>
    from ui.ui import UserInterface
  File "/home/pi/rpi_lcars-master/app/ui/ui.py", line 4, in <module>
    from ui.utils import sound
ImportError: No module named utils

**Comment by tobykurien** [comment] 2021-08-10 06:41
Duplicate of #38

**Closed as completed by tobykurien** 2021-08-10 06:41 UTC

**Comment by MCDevel** [comment] 2021-08-10 09:32
i tryed the solution from #38 but it still not working 
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "lcars.py", line 2, in <module>
    from ui.ui import UserInterface
  File "/home/pi/rpi_lcars-master/app/ui/ui.py", line 4, in <module>
    from ui.utils import sound
ImportError: No module named utils
